#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CLASS
version:      0.91
version_from: lib/CLASS.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
